#pragma once

#include "io.hpp"
#include "stm32f401xe.h"

#define LED_PORT (GPIOA)
#define LED_PIN (5) // PA5
#define LED_RCC_EN_MSK (RCC_AHB1ENR_GPIOAEN_Msk)
#define LED_RCC (RCC->AHB1ENR)

#define LED_BUTTON_PIN (13) // PC13
#define LED_BUTTON_PORT (GPIOC) // PC13
#define LED_BUTTON_RCC_EN_MSK (RCC_AHB1ENR_GPIOCEN_Msk)
#define LED_BUTTON_RCC (RCC->AHB1ENR)

#define ULT_TRIGGER_PORT (GPIOB)
#define ULT_TRIGGER_PIN (9)
#define ULT_TRIGGER_RCC (RCC->AHB1ENR)
#define ULT_TRIGGER_RCC_EN_MSK (RCC_AHB1ENR_GPIOBEN_Msk)

#define ULT_ECHO_PORT (GPIOB)
#define ULT_ECHO_PIN (8)
#define ULT_ECHO_RCC (RCC->AHB1ENR)
#define ULT_ECHO_RCC_EN_MSK (RCC_AHB1ENR_GPIOBEN_Msk)
#define ULT_ECHO_AFR_IX (1) // AFRH
#define ULT_ECHO_AFR_VAL (3) // AF03

#define ULT_TIM (TIM10)
#define ULT_TIM_RCC (RCC->APB2ENR)
#define ULT_TIM_RCC_EN_MSK (RCC_APB2ENR_TIM10EN_Msk)

#define ULT_BUTTON_PORT (GPIOA)
#define ULT_BUTTON_PIN (6)
#define ULT_BUTTON_RCC (RCC->AHB1ENR)
#define ULT_BUTTON_RCC_EN_MSK (RCC_AHB1ENR_GPIOAEN_Msk)

#define DELAY_TIM (TIM11)
#define DELAY_TIM_RCC (RCC->APB2ENR)
#define DELAY_TIM_RCC_EN_MSK (RCC_APB2ENR_TIM11EN_Msk)

#define DISPLAY_I2C_RCC (RCC->APB1ENR)
#define DISPLAY_I2C_RCC_EN (RCC_APB1ENR_I2C1EN)
#define DISPLAY_I2C_SCL_PORT (GPIOB)
#define DISPLAY_I2C_SCL_PIN (6)
#define DISPLAY_I2C_SDA_PORT (GPIOB)
#define DISPLAY_I2C_SDA_PIN (7)
#define DISPLAY_I2C (I2C1)
#define DISPLAY_I2C_SCL_AFR_IX (0) // AFRL
#define DISPLAY_I2C_SCL_AFR_VAL (4) // AF04 (I2C_SCL)
#define DISPLAY_I2C_SDA_AFR_IX (0) // AFRL
#define DISPLAY_I2C_SDA_AFR_VAL (4) // AF04 (I2C1_SDA)
